### ISSUE TITLE
[Enhancement] Merge fluent filetypes icons

### ISSUE THREAD

**Issue by FadeMind** [ozone10/7zip-Dark7zip#3]
Please merge (add) icons for **filetypes** from project https://github.com/Mr4Mike4/7-Zip-Filetype-Theme 
![20240723-1721741964](https://github.com/user-attachments/assets/40ced95f-c6e3-4b9e-b0e9-197056ad58fb)
They are stored in `7z.dll` in install root dir. 
Compiled DLLs are here: https://github.com/Mr4Mike4/7-Zip-Filetype-Theme/releases/latest
![20240723-1721742204](https://github.com/user-attachments/assets/bd527922-6dad-4cd5-aeff-78781236f2a6)

**Comment by CennoxX** [comment]
These icons have no licence.

**Comment by ozone10** [comment]
@FadeMind 
I don't provide `7z.dll` file, since it does not contain relevant modification in code from me.
Also as @CennoxX said those icons have no license, and I don't want to redistribute something I am not sure about.

I would also suggest to use "original" `7z.dll` and patch it with https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer (it also has those suggested icons) instead of those provided DLL files.
