### ISSUE TITLE
Detected as a virus

### ISSUE THREAD

**Issue by GeekCornerGH** [ozone10/7zip-Dark7zip#8]
Hi,

This project looks good, but for some reason my browser flagged it as a virus.

Also, [per Virustotal](https://www.virustotal.com/gui/file/4e37b89ed3ad948d4ce1bf562a270daa04e913de5e34810c8cc5ea2126536fd8), lots of antiviruses are flagging the `7z24.08-dark-x64.zip` file.

Is there a reason why?

Regards

**Comment by ozone10** [comment]
This is false positive. It is mainly from `7z.sfx`, which is optional as most users don't use it.
It's probably due to usage of IAT hooking, which is used for gridlines and comboboxex list colors.

For example [binaries](https://www.virustotal.com/gui/file/38b58f717042206f7c1b94d24de122092f73a9a58dccd65340e79630a4cb7913/) from [Github Action](https://github.com/ozone10/7zip-Dark7zip/actions/runs/10539835022) have different number of detection.

**Comment by ozone10** [comment]
Looking again at results, 7 AVs use bitdefender engine and this increases detection count with same result.

**Comment by SRC267** [comment]
Newest version still gives a virus detected message, so I'm unable to try this, The browser removes it.

**Comment by ozone10** [comment]
@SRC267 
again false positive, give it few days. Each time new 7z version is released some antivirus will detect it as threat, due to how their detection works.
https://www.virustotal.com/gui/file/d03a4dd5bebaa04e25668c848943be4f51ec42e8c71dccd6f6170fb34a7863e7/

**Comment by ozone10** [comment]
@SRC267 
as I said wait few days, or use other browser.
According to virus total there is detection, so you should be able to download it now.
